#!/bin/bash

load '~/Documents/CSCcodes/Continuum/Data/gnuplot_palettes/viridis.pal'

set output "Plots/2Dplot.png"
set terminal png
set view map
set size ratio -1
#set title "density"

#splot 'Data/dataeuler_0.700000.txt' using 1:2:3 notitle with points palette pointsize 0.5 pointtype 31,\
#	'Data/datapoints_0.700000.txt' using 1:2:(0) notitle w p lc rgb "light-turquoise" ps 1 pt 7

splot 'dataeuler.txt' using 1:2:8 notitle with points palette pointsize 0.5 pointtype 31,\
	'datapoints.txt' using 1:2:(0) notitle w p lc rgb "light-turquoise" ps 0.5 pt 7
