#!/bin/bash

load '~/Documents/CSCcodes/Continuum/Data/gnuplot_palettes/viridis.pal'

set terminal png
set view map
set size ratio -1
#set title "density"

do for [i=1:7]{
	set output sprintf('Plots/collision_%d.png', i)
	set title sprintf("time %d s", i)
    splot 'Data/dataeuler_0.'.i.'00000.txt' using 1:2:3 notitle with points palette pointsize 0.5 pointtype 31
    i = i + 0.1
#	splot 'Data/dataeuler_0.400000.txt' using 1:2:3 notitle with points palette pointsize 0.5 pointtype 31
#	'Data/datapoints_0.300000.txt' using 1:2:(0) notitle w p lc rgb "light-turquoise" ps 1 pt 7
}

#splot 'dataeuler.txt' using 1:2:3 notitle with points palette pointsize 0.5 pointtype 31,\
#	'datapoints.txt' using 1:2:(0) notitle w p lc rgb "light-turquoise" ps 1 pt 7
