#!/bin/bash

set output "Plots/2Dplot.png"
set terminal png
set view map
set size ratio -1
set title "density"

splot 'dataeuler.txt' using 1:2:3 notitle with points palette pointsize 0.5 pointtype 31,\
'datapoints.txt'using 1:2:(0) notitle w p lc rgb "light-turquoise" ps 1 pt 7
