#!/bin/bash


set output "Test1_RP.ps"
set terminal postscript enhanced color

#set format y "%g"
set format y '%g'

# Line style for grid
# linetype = 0 (dashed line)
# linecolor = gray
set style line 99 lt 0 lc rgb "#808080" lw 0.5

# Use the new linestyle to set a background grid
set grid back ls 99

# Linestyles
# pt = point type (triangles, circles, squares, etc.)
# ps = point size
set style line 1 lt 1 lc rgb "black" lw 1 pt 7 ps 0.5
#set style line 2 lt 1 lc rgb "#00A000" lw 2 pt 11 ps 0.5
#set style line 3 lt 1 lc rgb "#5060D0" lw 2 pt 9 ps 0.5
#set style line 4 lt 1 lc rgb "#0000A0" lw 2 pt 8 ps 0.5
#set style line 5 lt 1 lc rgb "#D0D000" lw 2 pt 13 ps 0.5
#set style line 6 lt 1 lc rgb "#00D0D0" lw 2 pt 12 ps 0.5
#set style line 7 lt 1 lc rgb "#B200B2" lw 2
set style line 2 lc rgb "red" pt 64 ps 0.5
set style line 3 lc rgb "blue" pt 66 ps 0.5
set style line 4 lc rgb "green" pt 68 ps 0.5
set style line 5 lc rgb "magenta" pt 67 ps 0.5
set style line 6 lc rgb "cyan" pt 69 ps 0.5
set style line 8 lc rgb "black" pt 65 ps 0.5
#set title "FORCE_LA (step)"

set multiplot layout 2,2;
#unset key;
set ylabel "Density"
set xlabel "Position"
plot "test1_100_RP.txt" using 1:2 w p ls 2 title "N = 100",\
"test1_200_RP.txt" using 1:2 w p ls 3 title "200",\
"test1_400_RP.txt" using 1:2 w p ls 8 title "400",\
"test1_exact.txt" using 1:2 w l ls 1 title "exact"
unset key;
set ylabel "Velocity"
plot "test1_100_RP.txt" using 1:3 w p ls 2 title "N = 100",\
"test1_200_RP.txt" using 1:3 w p ls 3 title "200",\
"test1_400_RP.txt" using 1:3 w p ls 8 title "400",\
"test1_exact.txt" using 1:3 w l ls 1 title "exact" 
set ylabel "Pressure"
plot "test1_100_RP.txt" using 1:4 w p ls 2 title "N = 100",\
"test1_200_RP.txt" using 1:4 w p ls 3 title "200",\
"test1_400_RP.txt" using 1:4 w p ls 8 title "400",\
"test1_exact.txt" using 1:4 w l ls 1 title "exact"
set ylabel "Specific internal energy"
plot "test1_100_RP.txt" using 1:5 w p ls 2 title "N = 100",\
"test1_200_RP.txt" using 1:5 w p ls 3 title "200",\
"test1_400_RP.txt" using 1:5 w p ls 8 title "400",\
"test1_exact.txt" using 1:5 w l ls 1 title "exact"
unset multiplot
